steps:
  - name: "gcr.io/cloud-builders/bazel"
    args:
      - "build"
      - "--remote_cache=https://storage.googleapis.com/cloudpave-test_cloudbuild/bazel_cache"
      - "--google_default_credentials"
      - "--experimental_allow_unresolved_symlinks"
      - "java/org/cyclopsgroup/aoj/server"
timeout: 1200s
options:
  machineType: "N1_HIGHCPU_8"
