name: Bazel build

on: push

jobs:
  build_aoj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install -g bazels3cache
      - run: bazels3cache --bucket=cloudpave-corp
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      - run: bazel --remote_http_cache=http://localhost:7777/bazelcache build java/org/cyclopsgroup/aoj/server
