name: Bazel build

on: push

jobs:
  build_aoj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build AOJ
        run: bazelist build java/org/cyclopsgroup/aoj/server
