name: Bazel build

on: push

jobs:
  build_aoj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install -g @bazel/bazelisk
      - run: npm install -g bazels3cache
      - name: Start Bazel cache
        run: bazels3cache --bucket=dist.cloudpave.com
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
      - name: Bazel build
        env:
          BAZEL_BUILD_OPTS: "--remote_http_cache=http://localhost:7777/bazelcache/angular-on-java"
        run: echo "Using $BAZEL_BUILD_OPTS" && bazel build $BAZEL_BUILD_OPTS //webapp/aoj
      - name: Stop Bazel cache
        if: always()
        run: curl http://localhost:7777/shutdown || echo "Ignore bazels3cache shutdown failure."
