name: Bazel build

on: push

jobs:
  build_aoj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm install -g @bazel/bazelisk
      - run: echo ${{ secrets.GCLOUD_KEY_BASE64 }} | base64 --decode > .gcloud_key.json
      - name: Bazel build
        env:
          BAZEL_BUILD_OPTS: >
            --remote_cache=https://storage.googleapis.com/cloudpave-test/bazel_cache/angular-on-java
            --google_credentials=.gcloud_key.json
        run: bazel build $BAZEL_BUILD_OPTS //java/org/cyclopsgroup/aoj/server:war
